<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            // Elektronik (category_id: 1)
            [
                'name' => 'Samsung Galaxy S23 Ultra',
                'description' => 'Smartphone flagship dengan kamera 200MP, layar Dynamic AMOLED 2X 6.8", prosesor Snapdragon 8 Gen 2, dan S Pen terintegrasi. Baterai 5000mAh dengan fast charging.',
                'image' => null,
                'price' => 18999000,
                'stock' => 25,
                'category_id' => 1,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'MacBook Air M2',
                'description' => 'Laptop ultra-tipis dengan chip Apple M2, layar Liquid Retina 13.6", RAM 8GB, SSD 256GB. Performa tinggi dengan desain elegan dan baterai tahan lama hingga 18 jam.',
                'image' => null,
                'price' => 16999000,
                'stock' => 15,
                'category_id' => 1,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sony WH-1000XM5',
                'description' => 'Headphone wireless premium dengan noise cancellation terbaik di kelasnya, audio Hi-Res, baterai 30 jam, dan fitur Adaptive Sound Control.',
                'image' => null,
                'price' => 5499000,
                'stock' => 40,
                'category_id' => 1,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'iPad Pro 11" M2',
                'description' => 'Tablet powerful dengan chip M2, layar Liquid Retina 11", support Apple Pencil generasi 2, dan kamera 12MP dengan LiDAR scanner.',
                'image' => null,
                'price' => 13999000,
                'stock' => 20,
                'category_id' => 1,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Fashion (category_id: 2)
            [
                'name' => 'Nike Air Jordan 1 Retro High',
                'description' => 'Sepatu sneakers ikonik dengan desain klasik, bahan kulit premium, cushioning Air-Sole, dan colorway OG. Perfect untuk gaya kasual maupun koleksi.',
                'image' => null,
                'price' => 2899000,
                'stock' => 50,
                'category_id' => 2,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Levi\'s 501 Original Jeans',
                'description' => 'Celana jeans klasik dengan potongan straight fit, bahan denim berkualitas tinggi, dan desain timeless yang cocok untuk berbagai gaya.',
                'image' => null,
                'price' => 1299000,
                'stock' => 75,
                'category_id' => 2,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Adidas Ultraboost 22',
                'description' => 'Running shoes dengan teknologi Boost cushioning, Primeknit+ upper breathable, dan Continental rubber outsole untuk traksi maksimal.',
                'image' => null,
                'price' => 2599000,
                'stock' => 35,
                'category_id' => 2,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Uniqlo Heattech Turtleneck',
                'description' => 'Kaos lengan panjang dengan teknologi Heattech untuk kehangatan ekstra, bahan stretch nyaman, dan desain minimalis yang versatile.',
                'image' => null,
                'price' => 299000,
                'stock' => 100,
                'category_id' => 2,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Makanan & Minuman (category_id: 3)
            [
                'name' => 'Arabica Coffee Beans 1kg',
                'description' => 'Biji kopi arabika premium dari Gayo, Aceh. Single origin dengan notes cokelat, karamel, dan hint buah-buahan. Roast level medium.',
                'image' => null,
                'price' => 185000,
                'stock' => 80,
                'category_id' => 3,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Japanese Matcha Powder 100g',
                'description' => 'Bubuk matcha grade A dari Jepang, kaya antioksidan, rasa umami yang khas, cocok untuk latte, smoothie, atau kue.',
                'image' => null,
                'price' => 275000,
                'stock' => 60,
                'category_id' => 3,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Organic Honey 500ml',
                'description' => 'Madu organik murni dari hutan Indonesia, tanpa tambahan gula, kaya nutrisi dan enzim alami. Dikemas dalam botol kaca.',
                'image' => null,
                'price' => 145000,
                'stock' => 90,
                'category_id' => 3,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Kesehatan & Kecantikan (category_id: 4)
            [
                'name' => 'SK-II Facial Treatment Essence',
                'description' => 'Essence kultus dengan 90% Pitera untuk kulit lebih cerah, kenyal, dan tekstur halus. Skincare favorit selebriti dunia.',
                'image' => null,
                'price' => 1850000,
                'stock' => 30,
                'category_id' => 4,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Cetaphil Gentle Skin Cleanser',
                'description' => 'Sabun pembersih wajah gentle untuk semua jenis kulit, pH balanced, non-comedogenic, dan recommended by dermatologist.',
                'image' => null,
                'price' => 189000,
                'stock' => 120,
                'category_id' => 4,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Vitamin C Serum 30ml',
                'description' => 'Serum vitamin C 20% dengan hyaluronic acid dan vitamin E, mencerahkan, anti-aging, dan melindungi dari radikal bebas.',
                'image' => null,
                'price' => 245000,
                'stock' => 85,
                'category_id' => 4,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Olahraga (category_id: 5)
            [
                'name' => 'Yoga Mat Premium 6mm',
                'description' => 'Matras yoga anti-slip dengan ketebalan 6mm, material TPE eco-friendly, dilengkapi carrying strap. Ukuran 183x61cm.',
                'image' => null,
                'price' => 385000,
                'stock' => 45,
                'category_id' => 5,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dumbbell Set 20kg',
                'description' => 'Set barbel 20kg dengan plate yang bisa disesuaikan, coating karet anti-slip, dan bar chrome berkualitas tinggi.',
                'image' => null,
                'price' => 899000,
                'stock' => 25,
                'category_id' => 5,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Resistance Band Set',
                'description' => 'Set 5 resistance band dengan level berbeda (Light-X Heavy), door anchor, ankle straps, dan carrying bag.',
                'image' => null,
                'price' => 249000,
                'stock' => 70,
                'category_id' => 5,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Rumah Tangga (category_id: 6)
            [
                'name' => 'Philips Air Fryer XXL',
                'description' => 'Air fryer kapasitas 7.3L dengan teknologi Rapid Air, digital touchscreen, 7 preset program, dan dishwasher safe.',
                'image' => null,
                'price' => 2499000,
                'stock' => 20,
                'category_id' => 6,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tefal Jamie Oliver Pan Set',
                'description' => 'Set panci dan wajan premium dengan coating titanium non-stick, thermo-spot indicator, dan handle ergonomis.',
                'image' => null,
                'price' => 1799000,
                'stock' => 15,
                'category_id' => 6,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dyson V15 Vacuum Cleaner',
                'description' => 'Vacuum cleaner cordless dengan laser detection, LCD screen, HEPA filtration, dan runtime hingga 60 menit.',
                'image' => null,
                'price' => 12999000,
                'stock' => 8,
                'category_id' => 6,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Buku & Alat Tulis (category_id: 7)
            [
                'name' => 'Atomic Habits - James Clear',
                'description' => 'Buku bestseller tentang bagaimana membangun kebiasaan baik dan menghilangkan kebiasaan buruk dengan sistem yang proven.',
                'image' => null,
                'price' => 125000,
                'stock' => 150,
                'category_id' => 7,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Moleskine Classic Notebook',
                'description' => 'Notebook premium hardcover dengan kertas ivory 70gsm, elastic closure, dan bookmark ribbon. Size Large (13x21cm).',
                'image' => null,
                'price' => 349000,
                'stock' => 80,
                'category_id' => 7,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Pilot G2 Gel Pen Set 12pcs',
                'description' => 'Set pulpen gel premium dengan tinta smooth, grip nyaman, dan berbagai pilihan warna. Perfect untuk journaling.',
                'image' => null,
                'price' => 189000,
                'stock' => 100,
                'category_id' => 7,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Mainan & Hobi (category_id: 8)
            [
                'name' => 'LEGO Star Wars Millennium Falcon',
                'description' => 'Set LEGO collector edition dengan 7541 pieces, detail akurat, termasuk 7 minifigures karakter Star Wars.',
                'image' => null,
                'price' => 12999000,
                'stock' => 5,
                'category_id' => 8,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Rubik\'s Cube 3x3 Speed Cube',
                'description' => 'Rubik cube profesional dengan corner cutting, smooth rotation, dan anti-pop technology. Cocok untuk speedcubing.',
                'image' => null,
                'price' => 149000,
                'stock' => 60,
                'category_id' => 8,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'DJI Mini 3 Pro Drone',
                'description' => 'Drone compact dengan kamera 4K/60fps, 3-axis gimbal, obstacle sensing, dan flight time hingga 34 menit.',
                'image' => null,
                'price' => 10999000,
                'stock' => 10,
                'category_id' => 8,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        Product::insert($products);
    }
}
